### ISSUE TITLE
Handle installer l10n

### ISSUE THREAD

**Issue by AntoineTurmel** [nightingale-media-player/nightingale-l10n#11]
We have to discuss on how to integrate l10n in the installer for both Windows & Mac OS X

**Comment by AntoineTurmel** [comment]
@mook @LukasSkywalker and Andrew were discussing it in 2009/2010 : 
http://bugzilla.songbirdnest.com/show_bug.cgi?id=16629

**Comment by AntoineTurmel** [comment]
Inno Setup support out of the box : Catalan, Czech, Danish, Finnish, French (Standard), German, Hebrew, Hungarian, Italian, Japanese, Norwegian (Bokmal), Polish, Portuguese (Brazil), Portuguese (Portugal), Russian, Serbian (Cyrillic), Serbian (Latin), Slovenian, Spanish, and Ukrainian

**Comment by rsjtdrjgfuzkfg** [comment]
@GeekShadow `French (Standard)` I'd prefer English as standard if you need one... :P

**Comment by AntoineTurmel** [comment]
@rsjtdrjgfuzkfg nope it mean the standard French not a derivate like Canadian/Breton...

**Comment by AntoineTurmel** [comment]
Fixed on Windows Installer since we now use InnoSetup:
https://github.com/nightingale-media-player/nightingale-hacking/blob/sb-trunk-oldxul/installer/windows/Nightingale.iss#L33

I think Mac OS X dmg doesn't have strings at all since it's just a drag and drop of an icon.
