### ISSUE TITLE
Remove specific Songbird strings

### ISSUE THREAD

**Issue by AntoineTurmel** [nightingale-media-player/nightingale-l10n#13]
Some Songbird strings could be removed such as champs credits (Support from the GetSatisfaction platform) or maybe replaced by forums/wiki contributors ?

See :
https://github.com/nightingale-media-player/nightingale-l10n/blob/master/locales/en-US/songbird/songbird.dtd#L840

What do you think ?

**Comment by rsjtdrjgfuzkfg** [comment]
If you can get a good list of our forums/wiki "champs", I think this is a good idea. If not, just removing sounds reasonable, keeping the regular SB credits, of course.

**Comment by AntoineTurmel** [comment]
So I added a list of our contributors a long time ago:
https://github.com/nightingale-media-player/nightingale-hacking/blob/sb-trunk-oldxul/app/content/html/aboutCredits.xhtml

I don't see any remaining specific Songbird strings we should delete or modify (aside unused/closed source strings)
