### ISSUE TITLE
GitHub Repo not allowed to contributions?

### ISSUE THREAD

**Issue by madduci** [nightingale-media-player/nightingale-l10n#20]
Hello
i am starting translating the locales for it-IT language, but when i try to commit on this repo, i got a 403 Unauthorized access.

**Comment by AntoineTurmel** [comment]
the Nightingale translation is not ready yet, feel free to complete/review the translation here :
http://translate.songbirdnest.com/languages/it

**Comment by ilikenwf** [comment]
And then, if you have stuff to commit, you can put in a pull request for GeekShadow to review and merge.

**Comment by rsjtdrjgfuzkfg** [comment]
@blackibiza84 probably we will request to not commit own changes, but let someone else review + pull request. See issue #15 for details. But as @GeekShadow stated, we're not ready yet ;)

@GeekShadow @ilikenwf close this issue?

**Comment by madduci** [comment]
ok..i started making the italian translation..once i'll finish, i'll send you the files

**Comment by AntoineTurmel** [comment]
@blackibiza84 
please contribute here for now :
http://translate.songbirdnest.com/languages/it

We will contact you once we migrate to the new translation system :)

**Comment by AntoineTurmel** [comment]
Closing this issue for now, I will told you when you can contribute here.

**Comment by AntoineTurmel** [comment]
@blackibiza84 we will soon open the translation, you can create an account here: http://beta.babelzilla.org if you want to participate :)
