### ISSUE TITLE
Some strings are surrounded by single quotes

### ISSUE THREAD

**Issue by AntoineTurmel** [nightingale-media-player/nightingale-l10n#26]
In songbird.dtd some strings are surrounded by single quotes while the rest of file uses double quotes.

See:
- https://github.com/nightingale-media-player/nightingale-l10n/blob/master/locales/en-US/songbird/songbird.dtd#L549
- https://github.com/nightingale-media-player/nightingale-l10n/blob/master/locales/en-US/songbird/songbird.dtd#L553
- https://github.com/nightingale-media-player/nightingale-l10n/blob/master/locales/en-US/songbird/songbird.dtd#L465

**Comment by rsjtdrjgfuzkfg** [comment]
Just as for #24 I'd propose some regex magic... see commit b008666ec09232ff456be0bb507bf904528c59d1 - that script solved that issues for me (locally, I did not commit the string changes).

**Comment by AntoineTurmel** [comment]
Manually fixed in 2adf0e9fbe4da2a4f8ecbef757959e7d67158066 to avoid big diff.
If someday POTI reopen SVB access we may do a patch...
