### ISSUE TITLE
Full backup of translate.songbirdnest.com

### ISSUE THREAD

**Issue by AntoineTurmel** [nightingale-media-player/nightingale-l10n#27]
I'm not sure who ran a backups of Songbird wiki & addons website... was it you @rsjtdrjgfuzkfg ? If so, could you run a backup using the same tool you used ?
Or if you don't have the time could give me what tool you use ?

We already have backups of localization, but I think it's better to have a full backup of website.

**Comment by rsjtdrjgfuzkfg** [comment]
Yup, was me. I started the process for translage.songbirdnest.com, the tool I used is the open HTTrack.

Any other songbird-websites I shall crawl if I have the tools running anyways?

**Comment by ilikenwf** [comment]
well, archive.org has the blog...both versions...

I'm also hoping Eric gets back the info to me as to who is selling off
Songbird's assets. If I/we/my LLC or whatever can buy the leftover
intellectual property and code affordably, I would then either maintain it
or open source it, or something like that...

**Comment by rsjtdrjgfuzkfg** [comment]
@GeekShadow HTTrack failed to get the drop-down-menu-links, so the translated strings are missing... still took about 3 days to run. I just started an update, but I guess it also won't get these links making the backup kinda useless.

**Comment by ilikenwf** [comment]
I suppose we should upload this to that backup subdomain or whatever?

**Comment by rsjtdrjgfuzkfg** [comment]
@ilikenwf if you want I'll upload it there once the update has been completed. However, it seems like the strings itself are mostly missing, as they are not on linked pages but only accessible via drop down menus and submit buttons...

**Comment by ilikenwf** [comment]
Interesting...

Maybe loading stuff via ajax or something?

**Comment by rsjtdrjgfuzkfg** [comment]
@ilikenwf via submitting of forms, the thing is that HTTrack doesn't support tracking that stuff :/

**Comment by ilikenwf** [comment]
Yeah, that's true...

Maybe we should use mechanical turk? haha

**Comment by AntoineTurmel** [comment]
Ok, so archive.org have some archives of it. Anyway now we have everything running for locales we doesn't need those archives :)
