### ISSUE TITLE
Make Nightingale Developer Credits Title translateable

### ISSUE THREAD

**Issue by freaktechnik** [nightingale-media-player/nightingale-l10n#31]
The title for the section of Nightingale Developers in the credits cannot be translated. This isn't good.

**Comment by AntoineTurmel** [comment]
fixed in https://github.com/nightingale-media-player/nightingale-hacking/commit/9cc9dd021a8af20b37a1d42e5a78450a8d3f1641
also the string should be translatable in like ~50 minutes on Babelzilla.
