### ISSUE TITLE
Improvements for nl

### ISSUE THREAD

**Issue by PanderMusubi** [nightingale-media-player/nightingale-l10n#35]
For:
- https://github.com/nightingale-media-player/nightingale-l10n/blob/master/locales/nl/songbird/songbird.properties
- https://github.com/nightingale-media-player/nightingale-l10n/blob/master/locales/nl/songbird/songbird.dtd
- https://github.com/nightingale-media-player/nightingale-l10n/blob/master/locales/nl/songbird/help.dtd
  
  "CD" should be written as "cd" in a sentence or "Cd" at the beginning of a sentence. Also compounds such as "CD-speler" and so on should be written as "cd-speler".

See http://woordenlijst.org/zoek/?q=cd&w=w and http://woordenlijst.org/zoek/?q=cd-speler&w=w

**Comment by freaktechnik** [comment]
See http://forum.getnightingale.com/thread-917.html and http://beta.babelzilla.org/projects/p/Nightingale/. Alternatively you can open a pull request on this repo, I believe, though it hasn't recently been synced with transifex,

**Comment by PanderMusubi** [comment]
Please assign it to the admin for the Dutch translation and/or sync it with transifax.

**Comment by freaktechnik** [comment]
This should be fixed, according to the localizer.
