### ISSUE TITLE
Include Mozilla strings for all locales

### ISSUE THREAD

**Issue by AntoineTurmel** [nightingale-media-player/nightingale-l10n#7]
Some locales doesn't have Mozilla strings, and so some parts of the software are shown in English (All Firefox common parts like Preferences, Downloads etc.).

Do we also stores those Mozilla strings here ? Or do we simply download them during the langpacks building ?
Mozilla strings are matching XULRunner 1.9.2 branch.

**Comment by AntoineTurmel** [comment]
Mozilla langpacks can be found here: http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/3.6.28/win32/xpi/
(I have checked, this is not platform specific even if it's under win32)

**Comment by freaktechnik** [comment]
I guess best would be to also download them in nightingale. We won't have to maintain even more locale strings.
If there are no strings for xulr, we might consider, if it's really worth keeping the locale, or if there is a similiar (probably less specific) locale.

**Comment by AntoineTurmel** [comment]
Well what we need is foreign .jar which is inside the .xpi, so I think I will make a script that download it before making the full langpack. But yeah no need to store Mozilla strings here.

**Comment by AntoineTurmel** [comment]
This is being tracked here now:
https://github.com/GeekShadow/nightingale-tools/issues/24

And it's almost resolved.
